name: Register Actions App
on: workflow_dispatch

jobs:
  register:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout
      - run: |
          echo "trigger" >> register.txt
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add register.txt
          git commit -m "Register GitHub Actions app"
          git push
